In [6]:
import ipyparallel as ipp

In [7]:
c = ipp.Client()

In [8]:
dv = c[:]

In [23]:
dv.scatter('a',range(16))

<AsyncResult: scatter>

In [32]:
%px y = [i**10 for i in a ]

In [36]:
dv.gather('y').get()

[0,
 1,
 1024,
 59049,
 1048576,
 9765625,
 60466176,
 282475249,
 1073741824,
 3486784401,
 10000000000,
 25937424601,
 61917364224,
 137858491849,
 289254654976,
 576650390625]

In [38]:
with dv.sync_imports():
    import numpy


importing numpy on engine(s)


In [39]:
%px a = numpy.random.rand(2,2)

In [46]:
%px numpy.linalg.eigvals(a)

Out[0:8]: array([-0.18568237,  1.25008658])

Out[1:8]: array([-0.03519019,  0.34918974])

Out[2:8]: array([ 0.43671341,  1.38766073])

Out[3:8]: array([-0.56268019,  0.75025854])

In [47]:
dv['w']

[array([-0.18568237,  1.25008658]),
 array([-0.03519019,  0.34918974]),
 array([ 0.43671341,  1.38766073]),
 array([-0.56268019,  0.75025854])]

In [48]:
%px print("hello")

[stdout:0] hello
[stdout:1] hello
[stdout:2] hello
[stdout:3] hello


In [49]:
%px %pylab inline

[stdout:0] Populating the interactive namespace from numpy and matplotlib
[stdout:1] Populating the interactive namespace from numpy and matplotlib
[stdout:2] Populating the interactive namespace from numpy and matplotlib
[stdout:3] Populating the interactive namespace from numpy and matplotlib


In [50]:
dv.scatter("numbers",range(10000))

<AsyncResult: scatter>

In [53]:
%px ans = [i**4 for i in numbers]

In [54]:
result = dv['ans']

In [55]:
result

[[0,
  1,
  16,
  81,
  256,
  625,
  1296,
  2401,
  4096,
  6561,
  10000,
  14641,
  20736,
  28561,
  38416,
  50625,
  65536,
  83521,
  104976,
  130321,
  160000,
  194481,
  234256,
  279841,
  331776,
  390625,
  456976,
  531441,
  614656,
  707281,
  810000,
  923521,
  1048576,
  1185921,
  1336336,
  1500625,
  1679616,
  1874161,
  2085136,
  2313441,
  2560000,
  2825761,
  3111696,
  3418801,
  3748096,
  4100625,
  4477456,
  4879681,
  5308416,
  5764801,
  6250000,
  6765201,
  7311616,
  7890481,
  8503056,
  9150625,
  9834496,
  10556001,
  11316496,
  12117361,
  12960000,
  13845841,
  14776336,
  15752961,
  16777216,
  17850625,
  18974736,
  20151121,
  21381376,
  22667121,
  24010000,
  25411681,
  26873856,
  28398241,
  29986576,
  31640625,
  33362176,
  35153041,
  37015056,
  38950081,
  40960000,
  43046721,
  45212176,
  47458321,
  49787136,
  52200625,
  54700816,
  57289761,
  59969536,
  62742241,
  65610000,
  68574961,
  71639296,
  74805201,
 

In [58]:
dv.scatter('vr',range(10000))

<AsyncResult: scatter>

In [61]:
%px ans = [i**5 for i in vr]


In [64]:
dv.gather('ans').get()

[0,
 1,
 32,
 243,
 1024,
 3125,
 7776,
 16807,
 32768,
 59049,
 100000,
 161051,
 248832,
 371293,
 537824,
 759375,
 1048576,
 1419857,
 1889568,
 2476099,
 3200000,
 4084101,
 5153632,
 6436343,
 7962624,
 9765625,
 11881376,
 14348907,
 17210368,
 20511149,
 24300000,
 28629151,
 33554432,
 39135393,
 45435424,
 52521875,
 60466176,
 69343957,
 79235168,
 90224199,
 102400000,
 115856201,
 130691232,
 147008443,
 164916224,
 184528125,
 205962976,
 229345007,
 254803968,
 282475249,
 312500000,
 345025251,
 380204032,
 418195493,
 459165024,
 503284375,
 550731776,
 601692057,
 656356768,
 714924299,
 777600000,
 844596301,
 916132832,
 992436543,
 1073741824,
 1160290625,
 1252332576,
 1350125107,
 1453933568,
 1564031349,
 1680700000,
 1804229351,
 1934917632,
 2073071593,
 2219006624,
 2373046875,
 2535525376,
 2706784157,
 2887174368,
 3077056399,
 3276800000,
 3486784401,
 3707398432,
 3939040643,
 4182119424,
 4437053125,
 4704270176,
 4984209207,
 5277319168,
 5584059449,
 5